---
exp_name: ENet_Cityscapes
agent: Agent
mode: test
cuda: true
gpu_device: 0
seed: 1337
num_classes: 19
ignore_index: 19
class_weights: "./pretrained_weights/voc2012_256_class_weights.npy"
img_size: 256
input_channels: 3
imagenet_nclasses: 1000
pretrained_encoder: true
pretrained_model_path: "./pretrained_weights/erfnet_encoder_pretrained.pth.tar"
learning_rate: 0.0005 
learning_rate_patience: 100
weight_decay: 0.0002
eps: 1.0e-08
betas:
- 0.9
- 0.999
gamma: 0.98
momentum: 0.98
batch_size: 16
max_epoch: 150
validate_every: 2
checkpoint_file: checkpoint.pth.tar
checkpoint_dir: "/kaggle/working/"
data_loader: VOCDataLoader
data_root: "./data/pascal_voc_seg/"
data_loader_workers: 4
pin_memory: true
async_loading: true
train_X: "/kaggle/input/cityscape-data/train_X.npy"
train_y: "/kaggle/input/cityscape-data/train_y.npy"
val_X: "/kaggle/input/cityscape-data/val_X.npy"
val_y: "/kaggle/input/cityscape-data/val_y.npy"
epochs: 300 